### ISSUE TITLE
[BUG] Installation failing

### ISSUE THREAD

**Issue by c0zm0** [inonoob/pirowflo#71]
Hi,

just tried the installation on a fresh raspi zero w with bullseye (32bit).

Building wheels for collected packages: pillow
  Building wheel for pillow (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp_octye1p_in_process.py build_wheel /tmp/tmpy8rguft7
       cwd: /tmp/pip-install-bh38l34k/pillow_efbb9bc5e7cc484bb15ccdfd966e4f9d
  Complete output (203 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv6l-cpython-39
  creating build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_util.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/__init__.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_deprecate.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/FitsImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_binary.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/QoiImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_typing.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_version.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/Image.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/features.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/__main__.py -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv6l-cpython-39/PIL
  running egg_info
  writing src/pillow.egg-info/PKG-INFO
  writing dependency_links to src/pillow.egg-info/dependency_links.txt
  writing requirements to src/pillow.egg-info/requires.txt
  writing top-level names to src/pillow.egg-info/top_level.txt
  reading manifest file 'src/pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no files found matching '*.txt'
  warning: no files found matching '.flake8'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.clang-format'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching 'renovate.json'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  no previously-included directories found matching 'wheels'
  adding license file 'LICENSE'
  writing manifest file 'src/pillow.egg-info/SOURCES.txt'
  copying src/PIL/_imagingcms.pyi -> build/lib.linux-armv6l-cpython-39/PIL
  copying src/PIL/_imagingft.pyi -> build/lib.linux-armv6l-cpython-39/PIL
  running build_ext

  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "<string>", line 989, in <module>
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-agp9k3e7/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
      _build_ext.run(self)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "<string>", line 812, in build_extensions
  __main__.RequiredDependencyException: jpeg

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/tmp_octye1p_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmp_octye1p_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp_octye1p_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-install-bh38l34k/pillow_efbb9bc5e7cc484bb15ccdfd966e4f9d/_custom_build/backend.py", line 55, in build_wheel
      return super().build_wheel(wheel_directory, config_settings, metadata_directory)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 404, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-install-bh38l34k/pillow_efbb9bc5e7cc484bb15ccdfd966e4f9d/_custom_build/backend.py", line 49, in run_setup
      return super().run_setup(setup_script)
    File "/tmp/pip-build-env-agp9k3e7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 1005, in <module>
  __main__.RequiredDependencyException:

  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  ----------------------------------------
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow which use PEP 517 and cannot be installed directly

-------------------------------------------------------
check for Ant+ dongle in order to set udev rules
Load the Ant+ dongle with FTDI driver
and ensure that the user pi has access to
-------------------------------------------------------

No Ant stick found !
----------------------------------------------
 add user to the group bluetoot and dialout
----------------------------------------------

-----------------------------------------------
 Change bluetooth name of the pi to PiRowFlo
-----------------------------------------------

------------------------------------------------------
 configuring web interface on http://pirowflo:9001
------------------------------------------------------

rm: cannot remove '/tmp/pirowflo*': No such file or directory
rm: cannot remove '/tmp/supervisord.log': No such file or directory

I had an ANT+ stick present at installation.

Running piroflo after rebooot fails:

~/pirowflo/src $ python3 waterrowerthreads.py -h
Traceback (most recent call last):
  File "/home/pi/pirowflo/src/waterrowerthreads.py", line 33, in <module>
    from adapters.ant import waterrowerant
  File "/home/pi/pirowflo/src/adapters/ant/waterrowerant.py", line 4, in <module>
    from . import antdongle as ant
  File "/home/pi/pirowflo/src/adapters/ant/antdongle.py", line 12, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'

Is there a chance that this project will get an update/fix in the near future?

**Comment by pc1246** [comment]
Hi
Did you fix this problem? I would like to use this software as well!
Regards Christoph

**Comment by olaims** [comment]
same problem

**Comment by elp3dr0** [comment]
The latest code hopefully fixes installation issues. I don't have a zero, but it works on a Pi 3. Please try again and report back so that the bug report be closed. Thanks!

**Comment by inonoob** [comment]
@elp3dr0 thank you for fixing the code and updating the repo !

**Comment by oldgitdaddy** [comment]
Hi @elp3dr0,
The logs are the same as from the original author of this issue. I run a raspi zero 2W with the latest raspbian OS.
```
Operating System: Raspbian GNU/Linux 12 (bookworm)
Kernel: Linux 6.12.25+rpt-rpi-v6

```

For the time being I remove the following line from requirements.txt:
`luma.oled==3.14.0`
With this the installation works, as luma oled is included for rendering of the on computer display, which the zero does not have.

I will let you know, if I can get it to work on the rower, the webserver for configuring at least is already starting.

**Comment by elp3dr0** [comment]
In this case, the luma.oled package is used for the little oled screen which inonoob attached to the GPIO pins. As both the RPi3 and Zero support GPIO, I'm surprised that the Zero behaves differently. 
#Potential Cause#
 Taking a closer look at the OP's wheel logs it seems like the zero is trying to build wheel from source, and is getting stuck because it's is missing JPEG development libraries. (which presumably are needed for the oled package?) 
#Potential Fix#
Google's Gemini suggests sudo apt install libjpeg-dev as a potential system package (apt not pip) to provide the required development libraries for JPEG.

If, however, you decide simply to remove luma.oled, you could experiment with commenting out or removing the 'setup screen setting to start up at boot ' section from the install script. That configures a systemd service to start at boot that will likely need the luma.oled package and so might fail. Hopefully it won't affect the main routine though because at first glance it is just a background service.
